
-- Create table

CREATE DATABASE IF NOT EXISTS COMPTA;
USE COMPTA;

CREATE TABLE IF NOT EXISTS FOURNISSEUR (
    ID INT NOT NULL PRIMARY KEY, 
    NOM VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS ARTICLE (
    ID INT NOT NULL PRIMARY KEY, 
    REF VARCHAR(13) NOT NULL, 
    DESIGNATION VARCHAR(255) NOT NULL, 
    PRIX DECIMAL(7,2) NOT NULL, 
    ID_FOU INT NOT NULL,
    CONSTRAINT FK_ARTICLE_FOU FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID)
);

CREATE TABLE IF NOT EXISTS BON (
    ID INT NOT NULL PRIMARY KEY, 
    NUMERO INT NOT NULL, 
    DATE_CMDE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    DELAI INT NOT NULL, 
    ID_FOU INT NOT NULL,
    CONSTRAINT FK_BON_FOU FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID)
);

CREATE TABLE IF NOT EXISTS COMPO (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    ID_ART INT NOT NULL, 
    ID_BON INT NOT NULL, 
    QTE INT NOT NULL,
    CONSTRAINT FK_COMPO_ART FOREIGN KEY (ID_ART) REFERENCES ARTICLE(ID),
    CONSTRAINT FK_COMPO_BON FOREIGN KEY (ID_BON) REFERENCES BON(ID)
);

-- isert data

--Fournisseur
INSERT INTO FOURNISSEUR (ID, NOM) VALUES (1, 'Française d''Imports');

INSERT INTO FOURNISSEUR (ID, NOM) VALUES (2, 'FDMSA');

INSERT INTO FOURNISSEUR (ID, NOM) VALUES (3, 'Dubois & Fils');

-- ou 

INSERT INTO FOURNISSEUR (ID, NOM) 
VALUES 
(1, 'Française d''Imports'),
(2, 'FDM SA'),
(3, 'Dubois & Fils');




--Compo
INSERT INTO COMPO (ID_ART, ID_BON, QTE) VALUES (1, 1, 3);

INSERT INTO COMPO (ID_ART, ID_BON, QTE) VALUES (5, 1, 4);

INSERT INTO COMPO (ID_ART, ID_BON, QTE) VALUES (7, 1, 1);

-- ou 

INSERT INTO COMPO (ID_ART, ID_BON, QTE) VALUES
(1, 1, 3),  
(5, 1, 4), 
(7, 1, 1);





